/*
 * Threading / lifetime notes:
 * - Client / Session / Op handles may be shared across threads.
 * - Request / StreamingResponse are single-owner handles and must not be driven concurrently.
 * - Borrowed pointers returned by getters remain valid until the owning handle is freed, or until
 *   the next mutating stream read for lk_streaming_response_t chunk views.
 * - All handles must be released with their matching free function.
 */


#ifndef LKREQUEST_H
#define LKREQUEST_H

/* Warning: this file is autogenerated by cbindgen. Do not edit manually. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef struct lk_client_t lk_client_t;
typedef struct lk_client_builder_t lk_client_builder_t;
typedef struct lk_session_t lk_session_t;
typedef struct lk_session_builder_t lk_session_builder_t;
typedef struct lk_request_t lk_request_t;
typedef struct lk_response_t lk_response_t;
typedef struct lk_streaming_response_t lk_streaming_response_t;
typedef struct lk_error_t lk_error_t;
typedef struct lk_op_t lk_op_t;
typedef struct lk_proxy_pool_t lk_proxy_pool_t;
typedef struct lk_proxy_pool_builder_t lk_proxy_pool_builder_t;
typedef struct lk_proxy_guard_t lk_proxy_guard_t;
typedef struct lk_socks5_udp_probe_report_t lk_socks5_udp_probe_report_t;
typedef struct lk_session_pool_t lk_session_pool_t;
typedef struct lk_session_pool_builder_t lk_session_pool_builder_t;
typedef struct lk_session_pool_guard_t lk_session_pool_guard_t;
typedef struct lk_multipart_t lk_multipart_t;

typedef struct lk_bytes_view_t {
  const uint8_t* ptr;
  size_t len;
} lk_bytes_view_t;

#define LK_ACCEPT_ENCODING_GZIP 0x01
#define LK_ACCEPT_ENCODING_BR 0x02
#define LK_ACCEPT_ENCODING_DEFLATE 0x04
#define LK_ACCEPT_ENCODING_ZSTD 0x08


enum lk_status_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_OK = 0,
  LK_ERR = -1,
};
#ifndef __cplusplus
typedef int32_t lk_status_t;
#endif // __cplusplus

enum lk_dns_config_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_DNS_SYSTEM = 0,
  LK_DNS_GOOGLE = 1,
  LK_DNS_GOOGLE_HTTPS = 2,
  LK_DNS_CLOUDFLARE = 3,
  LK_DNS_CLOUDFLARE_HTTPS = 4,
  LK_DNS_QUAD9 = 5,
  LK_DNS_QUAD9_HTTPS = 6,
};
#ifndef __cplusplus
typedef int32_t lk_dns_config_t;
#endif // __cplusplus

enum lk_error_code_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_ERR_UNKNOWN = 1,
  LK_ERR_INVALID_ARGUMENT = 2,
  LK_ERR_INTERNAL_PANIC = 3,
  LK_ERR_STREAM_CLOSED = 4,
  LK_ERR_INVALID_HANDLE = 5,
  LK_ERR_BUSY = 6,
  LK_ERR_RESOURCE_LIMIT_EXCEEDED = 7,
  LK_ERR_INVALID_CONFIG = 8,
  LK_ERR_NOT_FOUND = 9,
  LK_ERR_DECOMPRESSION_FAILED = 10,
  LK_ERR_TLS = 11,
  LK_ERR_HTTP = 12,
  LK_ERR_H2 = 13,
  LK_ERR_IO = 14,
  LK_ERR_PROXY = 15,
  LK_ERR_CONNECTION = 16,
  LK_ERR_TIMEOUT = 17,
  LK_ERR_TOO_MANY_REDIRECTS = 18,
  LK_ERR_POOL = 19,
  LK_ERR_URL_PARSE = 20,
  LK_ERR_STATUS = 21,
  LK_ERR_QUIC = 22,
  LK_ERR_H3 = 23,
};
#ifndef __cplusplus
typedef int32_t lk_error_code_t;
#endif // __cplusplus

enum lk_phase_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_PHASE_NONE = 0,
  LK_PHASE_DNS_RESOLUTION = 1,
  LK_PHASE_TCP_CONNECT = 2,
  LK_PHASE_PROXY_TUNNEL = 3,
  LK_PHASE_TLS_HANDSHAKE = 4,
  LK_PHASE_H2_NEGOTIATION = 5,
  LK_PHASE_H2C_UPGRADE = 6,
  LK_PHASE_HTTP_REQUEST = 7,
  LK_PHASE_QUIC_HANDSHAKE = 8,
  LK_PHASE_H3_NEGOTIATION = 9,
  LK_PHASE_QUIC_FALLBACK = 10,
};
#ifndef __cplusplus
typedef int32_t lk_phase_t;
#endif // __cplusplus

enum lk_op_state_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_OP_IN_PROGRESS = 0,
  LK_OP_COMPLETED_OK = 1,
  LK_OP_COMPLETED_ERR = 2,
  LK_OP_CANCELLED = 3,
  LK_OP_CONSUMED = 4,
};
#ifndef __cplusplus
typedef int32_t lk_op_state_t;
#endif // __cplusplus

enum lk_rotation_strategy_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_ROTATION_ROUND_ROBIN = 0,
  LK_ROTATION_RANDOM = 1,
};
#ifndef __cplusplus
typedef int32_t lk_rotation_strategy_t;
#endif // __cplusplus

enum lk_preferred_http_version_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_PREFERRED_HTTP_VERSION_AUTO = 0,
  LK_PREFERRED_HTTP_VERSION_HTTP1_ONLY = 10,
  LK_PREFERRED_HTTP_VERSION_HTTP2_ONLY = 20,
  LK_PREFERRED_HTTP_VERSION_HTTP3_ONLY = 30,
  LK_PREFERRED_HTTP_VERSION_HTTP3_WITH_FALLBACK = 31,
};
#ifndef __cplusplus
typedef int32_t lk_preferred_http_version_t;
#endif // __cplusplus

enum lk_http_version_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_HTTP_VERSION_UNKNOWN = 0,
  LK_HTTP_VERSION_10 = 10,
  LK_HTTP_VERSION_11 = 11,
  LK_HTTP_VERSION_2 = 20,
  LK_HTTP_VERSION_3 = 30,
};
#ifndef __cplusplus
typedef int32_t lk_http_version_t;
#endif // __cplusplus

enum lk_negotiated_http_version_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_NEGOTIATED_HTTP_VERSION_10 = 10,
  LK_NEGOTIATED_HTTP_VERSION_11 = 11,
  LK_NEGOTIATED_HTTP_VERSION_2 = 20,
  LK_NEGOTIATED_HTTP_VERSION_3 = 30,
};
#ifndef __cplusplus
typedef int32_t lk_negotiated_http_version_t;
#endif // __cplusplus

enum lk_socks5_udp_probe_mode_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_SOCKS5_UDP_PROBE_ASSOCIATE_ONLY = 0,
  LK_SOCKS5_UDP_PROBE_DNS_ROUND_TRIP = 1,
};
#ifndef __cplusplus
typedef int32_t lk_socks5_udp_probe_mode_t;
#endif // __cplusplus

enum lk_socks5_udp_probe_phase_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_SOCKS5_UDP_PROBE_PHASE_NOT_SOCKS5 = 0,
  LK_SOCKS5_UDP_PROBE_PHASE_UDP_ASSOCIATE = 1,
  LK_SOCKS5_UDP_PROBE_PHASE_UDP_ROUND_TRIP = 2,
};
#ifndef __cplusplus
typedef int32_t lk_socks5_udp_probe_phase_t;
#endif // __cplusplus

enum lk_socks5_udp_probe_support_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  LK_SOCKS5_UDP_SUPPORT_NOT_SOCKS5 = 0,
  LK_SOCKS5_UDP_SUPPORT_ASSOCIATE_OK = 1,
  LK_SOCKS5_UDP_SUPPORT_RELAY_OK = 2,
  LK_SOCKS5_UDP_SUPPORT_UNSUPPORTED = 3,
  LK_SOCKS5_UDP_SUPPORT_FAILED = 4,
};
#ifndef __cplusplus
typedef int32_t lk_socks5_udp_probe_support_t;
#endif // __cplusplus

/**
 * C-style DNS resolver used by `ClientBuilder`.
 *
 * # Callback contract
 *
 * Callbacks are invoked on the library runtime thread and must return
 * synchronously. They must not block on network I/O or other FFI calls.
 *
 * ## `resolve`
 *
 * Returns a borrowed JSON string containing an array of socket-address
 * strings, for example:
 *
 * `["127.0.0.1:443", "[2606:4700:4700::1111]:443"]`
 *
 * The library copies/parses the JSON immediately. Returning `LK_ERR` is
 * treated as a resolution failure.
 *
 * ## `lookup_https`
 *
 * Optional. Returns a borrowed JSON value matching `lkrequest::HttpsRecord`,
 * or an empty/null output to indicate "no HTTPS record". Returning `LK_ERR`
 * is treated as a lookup failure.
 *
 * ## `destroy`
 *
 * Called once when the resolver is dropped by the builder/client. May be
 * `NULL` if no cleanup is needed.
 */
typedef struct lk_dns_resolver_t {
  void *context;
  lk_status_t (*resolve)(void *context,
                         const char *host_ptr,
                         size_t host_len,
                         uint16_t port,
                         const char **out_json_ptr,
                         size_t *out_json_len);
  lk_status_t (*lookup_https)(void *context,
                              const char *host_ptr,
                              size_t host_len,
                              const char **out_json_ptr,
                              size_t *out_json_len);
  void (*destroy)(void *context);
} lk_dns_resolver_t;

/**
 * C-style callback sink for forwarding logs into the host language.
 */
typedef void (*lk_log_callback_t)(void *context,
                                  int32_t level,
                                  const char *target,
                                  const char *message);

typedef struct lk_chunk_view_t {
  const uint8_t *data;
  size_t len;
  bool is_final;
} lk_chunk_view_t;

/**
 * C-style proxy provider used by ProxyPool / SessionPool builders.
 *
 * # Callback contract
 *
 * All callbacks (`next_proxy`, `len`, `is_dynamic`) **must return synchronously
 * and quickly**. They are invoked on the library's internal runtime thread and
 * must not perform blocking I/O, network requests, or wait on locks held by
 * other FFI calls. Data should be pre-loaded in memory (e.g. a list of URLs
 * with an atomic index).
 *
 * ## `next_proxy` — borrowed pointer semantics
 *
 * The string written to `out_url_ptr` / `out_url_len` is **borrowed**: the
 * library copies the data immediately before the callback returns. The pointer
 * is invalidated the moment `next_proxy` returns; the caller (Rust side) will
 * never dereference it afterwards. This means:
 *
 * - **Go (cgo):** you may point into a Go `[]byte` pinned with
 *   `runtime.Pinner` (Go 1.21+); unpin after the callback returns.
 * - **Go (purego):** use a pre-allocated C buffer that you overwrite each call.
 * - **C/C++:** a stack or static buffer is fine.
 * - You do **not** need to `malloc` or transfer ownership.
 *
 * ## `destroy`
 *
 * Called once when the pool or builder that owns this provider is freed.
 * May be `NULL` if no cleanup is needed.
 */
typedef struct lk_proxy_provider_t {
  void *context;
  /**
   * Return the next proxy URL. The string pointed to by `out_url_ptr` is
   * borrowed and must remain valid only until this callback returns.
   * Return `LK_OK` on success or `LK_ERR` when no more proxies are available.
   */
  lk_status_t (*next_proxy)(void *context, const char **out_url_ptr, size_t *out_url_len);
  /**
   * Return the total number of known proxies. May return 0 for dynamic providers.
   */
  size_t (*len)(void *context);
  /**
   * Return `true` if this provider generates proxies dynamically. May be NULL (defaults to false).
   */
  bool (*is_dynamic)(void *context);
  /**
   * Called when the provider is no longer needed. May be NULL.
   */
  void (*destroy)(void *context);
} lk_proxy_provider_t;

typedef struct lk_string_view_t {
  const char *ptr;
  size_t len;
} lk_string_view_t;

typedef struct lk_form_pair_t {
  struct lk_string_view_t name;
  struct lk_string_view_t value;
} lk_form_pair_t;

/**
 * SOCKS5 UDP probe configuration.
 *
 * If `dns_server_host_ptr` is non-null, the probe encodes that host as the
 * SOCKS5 UDP target name (ATYP=domain). Otherwise `dns_server_addr_ptr` must
 * be a socket-address string such as `"1.1.1.1:53"`.
 */
typedef struct lk_socks5_udp_probe_config_t {
  lk_socks5_udp_probe_mode_t mode;
  uint64_t timeout_ms;
  const char *dns_server_addr_ptr;
  size_t dns_server_addr_len;
  const char *dns_server_host_ptr;
  size_t dns_server_host_len;
  const char *dns_query_ptr;
  size_t dns_query_len;
} lk_socks5_udp_probe_config_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t lk_abi_version(void);

lk_status_t lk_client_builder_add_ca_cert_file(lk_client_builder_t *builder, const char *path);

lk_status_t lk_client_builder_add_ca_cert_memory(lk_client_builder_t *builder,
                                                 const uint8_t *data_ptr,
                                                 size_t data_len);

lk_status_t lk_client_builder_add_cookie_order(lk_client_builder_t *builder,
                                               const char *name_ptr,
                                               size_t name_len);

lk_status_t lk_client_builder_add_default_header(lk_client_builder_t *builder,
                                                 const char *name_ptr,
                                                 size_t name_len,
                                                 const char *value_ptr,
                                                 size_t value_len);

lk_status_t lk_client_builder_add_h3_header_order(lk_client_builder_t *builder,
                                                  const char *name_ptr,
                                                  size_t name_len);

lk_status_t lk_client_builder_add_header_order(lk_client_builder_t *builder,
                                               const char *name_ptr,
                                               size_t name_len);

lk_status_t lk_client_builder_build(lk_client_builder_t *builder,
                                    lk_client_t **out_client,
                                    lk_error_t **out_err);

lk_status_t lk_client_builder_disable_http3(lk_client_builder_t *builder);

void lk_client_builder_free(lk_client_builder_t *builder);

lk_client_builder_t *lk_client_builder_new(void);

lk_status_t lk_client_builder_set_dns(lk_client_builder_t *builder, lk_dns_config_t dns_config);

lk_status_t lk_client_builder_set_dns_custom(lk_client_builder_t *builder,
                                             const char *addr_ptr,
                                             size_t addr_len);

lk_status_t lk_client_builder_set_dns_resolver(lk_client_builder_t *builder,
                                               struct lk_dns_resolver_t resolver);

lk_status_t lk_client_builder_set_ech_config(lk_client_builder_t *builder,
                                             const uint8_t *data_ptr,
                                             size_t data_len);

lk_status_t lk_client_builder_set_fallback_h2_to_h1(lk_client_builder_t *builder, bool enabled);

lk_status_t lk_client_builder_set_fallback_proxy_to_direct(lk_client_builder_t *builder,
                                                           bool enabled);

lk_status_t lk_client_builder_set_h2_preset(lk_client_builder_t *builder, const char *preset_name);

lk_status_t lk_client_builder_set_keylog_file(lk_client_builder_t *builder,
                                              const char *path_ptr,
                                              size_t path_len);

lk_status_t lk_client_builder_set_max_connections_per_session(lk_client_builder_t *builder,
                                                              size_t max_connections);

lk_status_t lk_client_builder_set_max_header_count(lk_client_builder_t *builder, size_t count);

lk_status_t lk_client_builder_set_max_header_size(lk_client_builder_t *builder, size_t size);

lk_status_t lk_client_builder_set_max_headers_total_size(lk_client_builder_t *builder, size_t size);

lk_status_t lk_client_builder_set_max_outstanding_ops(lk_client_builder_t *builder,
                                                      size_t max_outstanding_ops);

lk_status_t lk_client_builder_set_max_response_body_size(lk_client_builder_t *builder, size_t size);

lk_status_t lk_client_builder_set_min_transfer_rate(lk_client_builder_t *builder,
                                                    size_t bytes_per_sec,
                                                    uint64_t window_ms);

lk_status_t lk_client_builder_set_preset(lk_client_builder_t *builder, const char *preset_name);

lk_status_t lk_client_builder_set_quic_profile_json(lk_client_builder_t *builder,
                                                    const char *json_ptr,
                                                    size_t json_len);

lk_status_t lk_client_builder_set_retry_on_connection_close(lk_client_builder_t *builder,
                                                            bool enabled);

lk_status_t lk_client_builder_set_session_resumption_json(lk_client_builder_t *builder,
                                                          const char *json_ptr,
                                                          size_t json_len);

lk_status_t lk_client_builder_set_tcp_fingerprint_ja4t(lk_client_builder_t *builder,
                                                       const char *ja4t_ptr,
                                                       size_t ja4t_len);

lk_status_t lk_client_builder_set_timeout_dns(lk_client_builder_t *builder, uint64_t timeout_ms);

lk_status_t lk_client_builder_set_timeout_quic_connect(lk_client_builder_t *builder,
                                                       uint64_t timeout_ms);

lk_status_t lk_client_builder_set_timeout_tcp_connect(lk_client_builder_t *builder,
                                                      uint64_t timeout_ms);

lk_status_t lk_client_builder_set_timeout_tls_handshake(lk_client_builder_t *builder,
                                                        uint64_t timeout_ms);

lk_status_t lk_client_builder_set_timeout_total(lk_client_builder_t *builder, uint64_t timeout_ms);

lk_status_t lk_client_builder_set_timeout_ttfb(lk_client_builder_t *builder, uint64_t timeout_ms);

lk_status_t lk_client_builder_set_use_native_certs(lk_client_builder_t *builder, bool enabled);

lk_status_t lk_client_builder_set_verify(lk_client_builder_t *builder, bool enabled);

lk_client_t *lk_client_clone(const lk_client_t *client);

lk_status_t lk_client_fingerprint_info_json(const lk_client_t *client,
                                            const char **out_json_ptr,
                                            size_t *out_json_len,
                                            lk_error_t **out_err);

void lk_client_free(lk_client_t *client);

lk_status_t lk_client_new(const char *preset_name, lk_client_t **out_client, lk_error_t **out_err);

lk_status_t lk_client_new_default(lk_client_t **out_client, lk_error_t **out_err);

lk_error_code_t lk_error_code(const lk_error_t *err);

void lk_error_free(lk_error_t *err);

lk_status_t lk_error_get_diagnostics_json(const lk_error_t *err, const char **out_ptr);

int32_t lk_error_http_status(const lk_error_t *err);

bool lk_error_is_retryable(const lk_error_t *err);

lk_status_t lk_error_message(const lk_error_t *err, const char **out_ptr, size_t *out_len);

lk_phase_t lk_error_phase(const lk_error_t *err);

bool lk_feature_supported(const char *name);

const char *lk_library_version(void);

lk_status_t lk_log_init(const char *level_ptr, const char *file_path_ptr);

lk_status_t lk_log_init_callback(lk_log_callback_t callback, void *context, int32_t min_level);

lk_status_t lk_multipart_add_file(lk_multipart_t *multipart,
                                  const char *name_ptr,
                                  size_t name_len,
                                  const char *filename_ptr,
                                  size_t filename_len,
                                  const char *content_type_ptr,
                                  size_t content_type_len,
                                  const uint8_t *data_ptr,
                                  size_t data_len);

lk_status_t lk_multipart_add_text(lk_multipart_t *multipart,
                                  const char *name_ptr,
                                  size_t name_len,
                                  const char *value_ptr,
                                  size_t value_len);

void lk_multipart_free(lk_multipart_t *multipart);

lk_multipart_t *lk_multipart_new(void);

lk_status_t lk_op_cancel(lk_op_t *op);

void lk_op_free(lk_op_t *op);

lk_op_state_t lk_op_poll(const lk_op_t *op);

lk_status_t lk_op_take_chunk(lk_op_t *op, struct lk_chunk_view_t *out_chunk, lk_error_t **out_err);

lk_status_t lk_op_take_error(lk_op_t *op, lk_error_t **out_err);

lk_status_t lk_op_take_proxy_guard(lk_op_t *op, lk_proxy_guard_t **out_guard, lk_error_t **out_err);

lk_status_t lk_op_take_response(lk_op_t *op, lk_response_t **out_response, lk_error_t **out_err);

lk_status_t lk_op_take_session_pool_guard(lk_op_t *op,
                                          lk_session_pool_guard_t **out_guard,
                                          lk_error_t **out_err);

lk_status_t lk_op_take_socks5_udp_probe_report(lk_op_t *op,
                                               lk_socks5_udp_probe_report_t **out_report,
                                               lk_error_t **out_err);

lk_status_t lk_op_take_streaming_response(lk_op_t *op,
                                          lk_streaming_response_t **out_stream,
                                          lk_error_t **out_err);

lk_op_state_t lk_op_wait(const lk_op_t *op, uint64_t timeout_ms);

lk_status_t lk_preset_get_detail_json(const char *name_ptr,
                                      size_t name_len,
                                      const char **out_json_ptr,
                                      lk_error_t **out_err);

lk_status_t lk_preset_list_json(const char **out_json_ptr);

void lk_proxy_guard_free(lk_proxy_guard_t *guard);

lk_status_t lk_proxy_guard_mark_bad(lk_proxy_guard_t *guard);

lk_status_t lk_proxy_guard_url(const lk_proxy_guard_t *guard,
                               const char **out_ptr,
                               size_t *out_len);

lk_status_t lk_proxy_pool_acquire(const lk_proxy_pool_t *pool,
                                  lk_proxy_guard_t **out_guard,
                                  lk_error_t **out_err);

lk_status_t lk_proxy_pool_acquire_async(const lk_proxy_pool_t *pool,
                                        lk_op_t **out_op,
                                        lk_error_t **out_err);

lk_status_t lk_proxy_pool_acquire_fresh(const lk_proxy_pool_t *pool,
                                        const lk_proxy_guard_t *bad_guard,
                                        lk_proxy_guard_t **out_guard,
                                        lk_error_t **out_err);

lk_status_t lk_proxy_pool_builder_add_proxies(lk_proxy_pool_builder_t *builder,
                                              const char *const *url_ptrs,
                                              const size_t *url_lens,
                                              size_t count);

lk_status_t lk_proxy_pool_builder_add_proxy(lk_proxy_pool_builder_t *builder,
                                            const char *url_ptr,
                                            size_t url_len);

lk_status_t lk_proxy_pool_builder_build(lk_proxy_pool_builder_t *builder,
                                        lk_proxy_pool_t **out_pool,
                                        lk_error_t **out_err);

void lk_proxy_pool_builder_free(lk_proxy_pool_builder_t *builder);

lk_proxy_pool_builder_t *lk_proxy_pool_builder_new(void);

lk_status_t lk_proxy_pool_builder_set_bad_proxy_config(lk_proxy_pool_builder_t *builder,
                                                       uint32_t failure_threshold,
                                                       uint64_t window_ms,
                                                       uint64_t cooldown_ms,
                                                       uint32_t max_cooldowns);

lk_status_t lk_proxy_pool_builder_set_health_check(lk_proxy_pool_builder_t *builder,
                                                   const char *host_ptr,
                                                   size_t host_len,
                                                   uint16_t port,
                                                   uint64_t interval_ms,
                                                   uint64_t timeout_ms);

lk_status_t lk_proxy_pool_builder_set_max_proxies(lk_proxy_pool_builder_t *builder, size_t n);

lk_status_t lk_proxy_pool_builder_set_provider(lk_proxy_pool_builder_t *builder,
                                               struct lk_proxy_provider_t provider);

lk_status_t lk_proxy_pool_builder_set_proxy_buffer(lk_proxy_pool_builder_t *builder,
                                                   size_t capacity);

lk_status_t lk_proxy_pool_builder_set_rotation(lk_proxy_pool_builder_t *builder,
                                               lk_rotation_strategy_t strategy);

void lk_proxy_pool_free(lk_proxy_pool_t *pool);

lk_status_t lk_proxy_pool_mark_bad(const lk_proxy_pool_t *pool,
                                   const char *identity_ptr,
                                   size_t identity_len);

size_t lk_proxy_pool_max_concurrent(const lk_proxy_pool_t *pool);

lk_status_t lk_request_add_cookie_order(lk_request_t *request,
                                        const char *name_ptr,
                                        size_t name_len);

lk_status_t lk_request_add_h3_header_order(lk_request_t *request,
                                           const char *name_ptr,
                                           size_t name_len);

lk_status_t lk_request_add_header(lk_request_t *request,
                                  const char *name_ptr,
                                  size_t name_len,
                                  const char *value_ptr,
                                  size_t value_len);

lk_status_t lk_request_add_header_order(lk_request_t *request,
                                        const char *name_ptr,
                                        size_t name_len);

lk_status_t lk_request_add_query(lk_request_t *request,
                                 const char *key_ptr,
                                 size_t key_len,
                                 const char *value_ptr,
                                 size_t value_len);

void lk_request_free(lk_request_t *request);

lk_status_t lk_request_new(const lk_session_t *session,
                           const char *method_ptr,
                           size_t method_len,
                           const char *url_ptr,
                           size_t url_len,
                           lk_request_t **out_request,
                           lk_error_t **out_err);

lk_status_t lk_request_send(lk_request_t *request,
                            lk_response_t **out_response,
                            lk_error_t **out_err);

lk_status_t lk_request_send_async(lk_request_t *request, lk_op_t **out_op, lk_error_t **out_err);

lk_status_t lk_request_send_streaming(lk_request_t *request,
                                      lk_streaming_response_t **out_stream,
                                      lk_error_t **out_err);

lk_status_t lk_request_send_streaming_async(lk_request_t *request,
                                            lk_op_t **out_op,
                                            lk_error_t **out_err);

lk_status_t lk_request_set_accept_encoding(lk_request_t *request, uint8_t encoding_bits);

lk_status_t lk_request_set_auto_decompress(lk_request_t *request, bool enabled);

lk_status_t lk_request_set_basic_auth(lk_request_t *request,
                                      const char *username_ptr,
                                      size_t username_len,
                                      const char *password_ptr,
                                      size_t password_len);

lk_status_t lk_request_set_bearer_auth(lk_request_t *request,
                                       const char *token_ptr,
                                       size_t token_len);

lk_status_t lk_request_set_body_bytes(lk_request_t *request,
                                      const uint8_t *data_ptr,
                                      size_t data_len);

lk_status_t lk_request_set_cookie(lk_request_t *request,
                                  const char *name_ptr,
                                  size_t name_len,
                                  const char *value_ptr,
                                  size_t value_len);

lk_status_t lk_request_set_cookie_override(lk_request_t *request,
                                           const char *name_ptr,
                                           size_t name_len,
                                           const char *value_ptr,
                                           size_t value_len);

lk_status_t lk_request_set_form(lk_request_t *request,
                                const struct lk_form_pair_t *pairs_ptr,
                                size_t pairs_count);

lk_status_t lk_request_set_json_text(lk_request_t *request, const char *json_ptr, size_t json_len);

/**
 * Takes ownership of `multipart` on success. The caller must NOT call
 * `lk_multipart_free` after a successful return. On `LK_ERR`, ownership
 * is NOT transferred and the caller retains responsibility for freeing it.
 */
lk_status_t lk_request_set_multipart(lk_request_t *request, lk_multipart_t *multipart);

lk_status_t lk_request_set_preferred_http_version(lk_request_t *request,
                                                  lk_preferred_http_version_t version);

lk_status_t lk_request_set_proxy(lk_request_t *request, const char *proxy_ptr, size_t proxy_len);

lk_status_t lk_request_set_text_body(lk_request_t *request, const char *text_ptr, size_t text_len);

lk_status_t lk_request_set_timeout(lk_request_t *request, uint64_t timeout_ms);

lk_status_t lk_request_set_version(lk_request_t *request, lk_http_version_t version);

lk_status_t lk_response_body(const lk_response_t *response,
                             const uint8_t **out_ptr,
                             size_t *out_len);

int64_t lk_response_content_length(const lk_response_t *response);

lk_status_t lk_response_cookie_at(const lk_response_t *response,
                                  size_t index,
                                  const char **out_name_ptr,
                                  size_t *out_name_len,
                                  const char **out_value_ptr,
                                  size_t *out_value_len);

size_t lk_response_cookie_count(const lk_response_t *response);

lk_status_t lk_response_cookie_name_at(const lk_response_t *response,
                                       size_t index,
                                       const char **out_ptr,
                                       size_t *out_len);

lk_status_t lk_response_cookie_value_at(const lk_response_t *response,
                                        size_t index,
                                        const char **out_ptr,
                                        size_t *out_len);

lk_status_t lk_response_copy_body(const lk_response_t *response,
                                  uint8_t *buf,
                                  size_t buf_len,
                                  size_t *out_read_len);

lk_status_t lk_response_error_for_status(const lk_response_t *response, lk_error_t **out_err);

void lk_response_free(lk_response_t *response);

lk_status_t lk_response_get_diagnostics_json(const lk_response_t *response, const char **out_ptr);

lk_status_t lk_response_get_header_by_name(const lk_response_t *response,
                                           const char *name_ptr,
                                           size_t name_len,
                                           const uint8_t **out_ptr,
                                           size_t *out_len,
                                           lk_error_t **out_err);

size_t lk_response_header_count(const lk_response_t *response);

lk_status_t lk_response_header_name_at(const lk_response_t *response,
                                       size_t index,
                                       const char **out_ptr,
                                       size_t *out_len);

lk_status_t lk_response_header_value_at(const lk_response_t *response,
                                        size_t index,
                                        const uint8_t **out_ptr,
                                        size_t *out_len);

lk_status_t lk_response_negotiated_version(const lk_response_t *response,
                                           lk_negotiated_http_version_t *out_version);

lk_status_t lk_response_redirect_at(const lk_response_t *response,
                                    size_t index,
                                    const char **out_url_ptr,
                                    size_t *out_url_len,
                                    uint16_t *out_status);

size_t lk_response_redirect_count(const lk_response_t *response);

uint16_t lk_response_redirect_status_at(const lk_response_t *response, size_t index);

lk_status_t lk_response_redirect_url_at(const lk_response_t *response,
                                        size_t index,
                                        const char **out_ptr,
                                        size_t *out_len);

uint16_t lk_response_status(const lk_response_t *response);

lk_status_t lk_response_text(const lk_response_t *response,
                             const char **out_ptr,
                             size_t *out_len,
                             lk_error_t **out_err);

lk_status_t lk_response_url(const lk_response_t *response, const char **out_ptr, size_t *out_len);

lk_status_t lk_response_version(const lk_response_t *response, lk_http_version_t *out_version);

bool lk_response_was_redirected(const lk_response_t *response);

lk_status_t lk_session_builder_add_cookie_order(lk_session_builder_t *builder,
                                                const char *name_ptr,
                                                size_t name_len);

lk_status_t lk_session_builder_add_h3_header_order(lk_session_builder_t *builder,
                                                   const char *name_ptr,
                                                   size_t name_len);

lk_status_t lk_session_builder_add_header_order(lk_session_builder_t *builder,
                                                const char *name_ptr,
                                                size_t name_len);

lk_status_t lk_session_builder_build(lk_session_builder_t *builder,
                                     lk_session_t **out_session,
                                     lk_error_t **out_err);

lk_status_t lk_session_builder_disable_redirects(lk_session_builder_t *builder);

void lk_session_builder_free(lk_session_builder_t *builder);

lk_session_builder_t *lk_session_builder_new(const lk_client_t *client);

lk_status_t lk_session_builder_set_default_accept_encoding(lk_session_builder_t *builder,
                                                           uint8_t encoding_bits);

lk_status_t lk_session_builder_set_ech_config(lk_session_builder_t *builder,
                                              const uint8_t *data_ptr,
                                              size_t data_len);

lk_status_t lk_session_builder_set_http1_only(lk_session_builder_t *builder);

lk_status_t lk_session_builder_set_http2_only(lk_session_builder_t *builder);

lk_status_t lk_session_builder_set_http3_only(lk_session_builder_t *builder);

lk_status_t lk_session_builder_set_http3_with_fallback(lk_session_builder_t *builder);

lk_status_t lk_session_builder_set_idle_timeout(lk_session_builder_t *builder,
                                                uint64_t idle_timeout_ms);

lk_status_t lk_session_builder_set_max_connections(lk_session_builder_t *builder,
                                                   size_t max_connections);

lk_status_t lk_session_builder_set_max_redirects(lk_session_builder_t *builder,
                                                 uint32_t max_redirects);

lk_status_t lk_session_builder_set_proxy(lk_session_builder_t *builder,
                                         const char *proxy_ptr,
                                         size_t proxy_len);

lk_status_t lk_session_builder_set_retry_exponential(lk_session_builder_t *builder,
                                                     uint32_t max_retries,
                                                     uint64_t base_delay_ms,
                                                     uint64_t max_delay_ms,
                                                     bool jitter);

lk_status_t lk_session_builder_set_retry_fixed(lk_session_builder_t *builder,
                                               uint32_t max_retries,
                                               uint64_t interval_ms);

lk_status_t lk_session_clear_cookies(lk_session_t *session);

lk_session_t *lk_session_clone(const lk_session_t *session);

lk_status_t lk_session_connection_pool_clear(lk_session_t *session);

lk_status_t lk_session_connection_pool_stats(const lk_session_t *session,
                                             size_t *out_h2,
                                             size_t *out_h1,
                                             size_t *out_total,
                                             size_t *out_max,
                                             bool *out_at_capacity);

void lk_session_free(lk_session_t *session);

lk_status_t lk_session_get_cookie(const lk_session_t *session,
                                  const char *url_ptr,
                                  size_t url_len,
                                  const char *name_ptr,
                                  size_t name_len,
                                  const char **out_value_ptr,
                                  size_t *out_value_len,
                                  lk_error_t **out_err);

lk_status_t lk_session_get_cookies_json(const lk_session_t *session,
                                        const char *url_ptr,
                                        size_t url_len,
                                        const char **out_json_ptr);

lk_status_t lk_session_new(const lk_client_t *client,
                           lk_session_t **out_session,
                           lk_error_t **out_err);

lk_status_t lk_session_new_with_config(const lk_client_t *client,
                                       const char *proxy_ptr,
                                       size_t proxy_len,
                                       uint32_t max_redirects,
                                       lk_session_t **out_session,
                                       lk_error_t **out_err);

lk_status_t lk_session_pool_acquire(const lk_session_pool_t *pool,
                                    lk_session_pool_guard_t **out_guard,
                                    lk_error_t **out_err);

lk_status_t lk_session_pool_acquire_async(const lk_session_pool_t *pool,
                                          lk_op_t **out_op,
                                          lk_error_t **out_err);

lk_status_t lk_session_pool_acquire_fresh(const lk_session_pool_t *pool,
                                          const lk_session_pool_guard_t *bad_guard,
                                          lk_session_pool_guard_t **out_guard,
                                          lk_error_t **out_err);

lk_status_t lk_session_pool_builder_add_proxies(lk_session_pool_builder_t *builder,
                                                const char *const *url_ptrs,
                                                const size_t *url_lens,
                                                size_t count);

lk_status_t lk_session_pool_builder_add_proxy(lk_session_pool_builder_t *builder,
                                              const char *url_ptr,
                                              size_t url_len);

lk_status_t lk_session_pool_builder_build(lk_session_pool_builder_t *builder,
                                          lk_session_pool_t **out_pool,
                                          lk_error_t **out_err);

void lk_session_pool_builder_free(lk_session_pool_builder_t *builder);

lk_session_pool_builder_t *lk_session_pool_builder_new(const lk_client_t *client);

lk_status_t lk_session_pool_builder_set_bad_proxy_config(lk_session_pool_builder_t *builder,
                                                         uint32_t failure_threshold,
                                                         uint64_t window_ms,
                                                         uint64_t cooldown_ms,
                                                         uint32_t max_cooldowns);

lk_status_t lk_session_pool_builder_set_health_check(lk_session_pool_builder_t *builder,
                                                     const char *host_ptr,
                                                     size_t host_len,
                                                     uint16_t port,
                                                     uint64_t interval_ms,
                                                     uint64_t timeout_ms);

lk_status_t lk_session_pool_builder_set_idle_timeout(lk_session_pool_builder_t *builder,
                                                     uint64_t timeout_ms);

lk_status_t lk_session_pool_builder_set_max_sessions(lk_session_pool_builder_t *builder, size_t n);

lk_status_t lk_session_pool_builder_set_provider(lk_session_pool_builder_t *builder,
                                                 struct lk_proxy_provider_t provider);

lk_status_t lk_session_pool_builder_set_proxy_buffer(lk_session_pool_builder_t *builder,
                                                     size_t capacity);

lk_status_t lk_session_pool_builder_set_rotation(lk_session_pool_builder_t *builder,
                                                 lk_rotation_strategy_t strategy);

void lk_session_pool_free(lk_session_pool_t *pool);

void lk_session_pool_guard_free(lk_session_pool_guard_t *guard);

/**
 * The created request holds an internal reference to the guard's session.
 * The guard may be freed independently; the request remains valid.
 * The session is returned to the pool when both the guard and all
 * requests created from it have been freed.
 */
lk_status_t lk_session_pool_guard_request_new(const lk_session_pool_guard_t *guard,
                                              const char *method_ptr,
                                              size_t method_len,
                                              const char *url_ptr,
                                              size_t url_len,
                                              lk_request_t **out_request,
                                              lk_error_t **out_err);

lk_status_t lk_session_pool_mark_bad(const lk_session_pool_t *pool,
                                     const lk_session_pool_guard_t *guard);

lk_status_t lk_session_pool_stats(const lk_session_pool_t *pool, size_t *out_idle, size_t *out_max);

lk_status_t lk_session_preconnect(const lk_session_t *session,
                                  const char *url_ptr,
                                  size_t url_len,
                                  lk_error_t **out_err);

/**
 * Preconnect does not produce a response payload. On completion:
 * - `LK_OP_COMPLETED_OK`: preconnect succeeded; call `lk_op_free` directly.
 * - `LK_OP_COMPLETED_ERR`: use `lk_op_take_error` to retrieve the error.
 */
lk_status_t lk_session_preconnect_async(const lk_session_t *session,
                                        const char *url_ptr,
                                        size_t url_len,
                                        lk_op_t **out_op,
                                        lk_error_t **out_err);

lk_status_t lk_session_remove_cookie(lk_session_t *session,
                                     const char *url_ptr,
                                     size_t url_len,
                                     const char *name_ptr,
                                     size_t name_len);

lk_status_t lk_session_set_cookie(lk_session_t *session,
                                  const char *url_ptr,
                                  size_t url_len,
                                  const char *name_ptr,
                                  size_t name_len,
                                  const char *value_ptr,
                                  size_t value_len);

lk_status_t lk_session_set_cookie_with_attrs(lk_session_t *session,
                                             const char *url_ptr,
                                             size_t url_len,
                                             const char *name_ptr,
                                             size_t name_len,
                                             const char *value_ptr,
                                             size_t value_len,
                                             const char *path_ptr,
                                             size_t path_len,
                                             const char *domain_ptr,
                                             size_t domain_len,
                                             bool secure,
                                             bool http_only,
                                             lk_error_t **out_err);

lk_status_t lk_socks5_udp_probe(const lk_client_t *client,
                                const char *proxy_ptr,
                                size_t proxy_len,
                                const struct lk_socks5_udp_probe_config_t *config,
                                lk_socks5_udp_probe_report_t **out_report,
                                lk_error_t **out_err);

lk_status_t lk_socks5_udp_probe_async(const lk_client_t *client,
                                      const char *proxy_ptr,
                                      size_t proxy_len,
                                      const struct lk_socks5_udp_probe_config_t *config,
                                      lk_op_t **out_op,
                                      lk_error_t **out_err);

uint64_t lk_socks5_udp_probe_report_elapsed_ms(const lk_socks5_udp_probe_report_t *report);

lk_status_t lk_socks5_udp_probe_report_error(const lk_socks5_udp_probe_report_t *report,
                                             const char **out_ptr,
                                             size_t *out_len);

void lk_socks5_udp_probe_report_free(lk_socks5_udp_probe_report_t *report);

lk_status_t lk_socks5_udp_probe_report_json(const lk_socks5_udp_probe_report_t *report,
                                            const char **out_ptr,
                                            size_t *out_len);

lk_socks5_udp_probe_phase_t lk_socks5_udp_probe_report_phase(const lk_socks5_udp_probe_report_t *report);

lk_status_t lk_socks5_udp_probe_report_proxy(const lk_socks5_udp_probe_report_t *report,
                                             const char **out_ptr,
                                             size_t *out_len);

lk_status_t lk_socks5_udp_probe_report_relay_addr(const lk_socks5_udp_probe_report_t *report,
                                                  const char **out_ptr,
                                                  size_t *out_len);

lk_socks5_udp_probe_support_t lk_socks5_udp_probe_report_support(const lk_socks5_udp_probe_report_t *report);

lk_status_t lk_stream_close(lk_streaming_response_t *stream);

lk_status_t lk_stream_copy_chunk(const lk_streaming_response_t *stream,
                                 uint8_t *buf,
                                 size_t buf_len,
                                 size_t *out_read_len);

lk_status_t lk_stream_read(lk_streaming_response_t *stream,
                           struct lk_chunk_view_t *out_chunk,
                           lk_error_t **out_err);

lk_status_t lk_stream_read_async(lk_streaming_response_t *stream,
                                 lk_op_t **out_op,
                                 lk_error_t **out_err);

void lk_streaming_response_free(lk_streaming_response_t *stream);

lk_status_t lk_streaming_response_get_diagnostics_json(const lk_streaming_response_t *stream,
                                                       const char **out_ptr);

lk_status_t lk_streaming_response_get_header_by_name(const lk_streaming_response_t *stream,
                                                     const char *name_ptr,
                                                     size_t name_len,
                                                     const uint8_t **out_ptr,
                                                     size_t *out_len,
                                                     lk_error_t **out_err);

size_t lk_streaming_response_header_count(const lk_streaming_response_t *stream);

lk_status_t lk_streaming_response_header_name_at(const lk_streaming_response_t *stream,
                                                 size_t index,
                                                 const char **out_ptr,
                                                 size_t *out_len);

lk_status_t lk_streaming_response_header_value_at(const lk_streaming_response_t *stream,
                                                  size_t index,
                                                  const uint8_t **out_ptr,
                                                  size_t *out_len);

uint16_t lk_streaming_response_status(const lk_streaming_response_t *stream);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LKREQUEST_H */
